#!/bin/bash

# initialise locations
BASHINATE_HOME=~/.bashinate

# initialise elements remote and local
SCRIPTLETS_REMOTE=https://raw.github.com/DamonOehlman/bashinate/master/scriptlets
SCRIPTLETS_LOCAL=$BASHINATE_HOME/scriptlets

# ## require element *args
#
# The require function is used to include a particular element in the provisioning process.  For instance,
# if you wanted to orchestrate the installation of node then you would use a statement similar to the one
# below:
#
# ```bash
# require node
# ```
function require {
	# first look in an scriptlets directory relative to the current working directory
	el=$(pwd)/scriptlets/$1

	# if we don't have a cwd element override, use the local repository
	[[ -f $el ]] || el=$SCRIPTLETS_LOCAL/$1

	# if we don't have the required element, then abort
	if [[ ! -f $el ]]; then abort "Unable to require \"$1\" scriptlet."; fi

	# include the source file
	source $el
}

# ## abort msg
# 
# The abort function is used to exit the script with an error code and report the error
# on the console.
function abort {
	echo $1; exit 1
}

# ensure we have an ~/.orc directory
mkdir -p $SCRIPTLETS_LOCAL