#!/bin/bash

# initialise locations
BASHINATE_HOME=~/.bashinate

# initialise elements remote and local
ELEMENTS_REMOTE=https://raw.github.com/DamonOehlman/bashinate/master/elements
ELEMENTS_LOCAL=$BASHINATE_/elements

# ## require(element *args)
# The require function is used to include a particular element in the provisioning process.  For instance,
# if you wanted to orchestrate the installation of node then you would use a statement similar to the one
# below:
#
# ```bash
# require node
# ```
function require {
	# first look in an elements directory relative to the current working directory
	el=$(pwd)/elements/$1

	# if we don't have a cwd element override, use the local repository
	[[ -f $el ]] || el=$ELEMENTS_LOCAL/$1

	echo $el
}

# ensure we have an ~/.orc directory
mkdir -p $ELEMENTS_LOCAL