#!/bin/bash
PACKAGE_VERSION=${PACKAGE_VERSION-0.10.10}
PACKAGE_SOURCE=http://nodejs.org/dist/v$PACKAGE_VERSION/node-v$PACKAGE_VERSION.tar.gz

require packages build-essential

# if we don't have the latest node version, then install
echo "==> Checking Node version $PACKAGE_VERSION installed";
if [ ! -e $INSTALL_BASE/node/$PACKAGE_VERSION ]
then
	echo "==> Installing Node.js version $PACKAGE_VERSION"
	echo "- downloading source from $PACKAGE_SOURCE"

	cd /usr/src
	wget -nc --quiet $PACKAGE_SOURCE \
		|| (echo "!!! Unable to download node source files" & exit 1)

	tar xf node-v$PACKAGE_VERSION.tar.gz
	cd node-v$PACKAGE_VERSION

	# configure 
	echo "- configuring"
	./configure --prefix=$INSTALL_BASE/node/$PACKAGE_VERSION \
		|| (echo "!!! Unable to configure node build" & exit 1)

	# make and install
	echo "- compiling and installing"
	make && make install \
		|| (echo "!!! Unable to make node $PACKAGE_VERSION" & exit 1)
fi

# create node application links (if we have the version available)
if [ -e $INSTALL_BASE/node/$PACKAGE_VERSION ]
then
	ln -sf $INSTALL_BASE/node/$PACKAGE_VERSION/bin/node /usr/bin/node
	ln -sf $INSTALL_BASE/node/$PACKAGE_VERSION/bin/npm /usr/bin/npm
fi